### ISSUE TITLE
How to undo the deletion of worldID and lris code？

### ISSUE THREAD

**Issue by yimao009** [worldcoin/orb-software#111]
I accidentally deleted my world ID and lris code, and it said there is a 6-month cooling-off period. How can I cancel it?

**Comment by TheButlah** [comment]
Hi, thank you for your interest in the project! Unfortunately, github is a place for contributing to the code that runs on the orb. I think your question can best be answered by using the existing support center in the app.

On my app, I can the support section under the settings menu, which is accessed via the gear icon on the top right of the app.
