### ISSUE TITLE
Could fingerprint scanning and facial recognition be used for onboarding?

### ISSUE THREAD

**Issue by rajjanorkar** [worldcoin/orb-software#228]
I had a random thought – instead of using the special orb device for onboarding, could we consider using fingerprint and/or facial recognition for signups?

This idea came to mind as, in India, I can perform banking transactions with just fingerprint recognition. With billions of people already registered under the AADHAAR system, fingerprints seem sufficient to uniquely identify individuals.

**Comment by TheButlah** [comment]
Good question!
We elaborate on why we need custom hardware here:
https://whitepaper.worldcoin.org/#why-custom-hardware-is-needed

We explain why fingerprints are not a viable approach here:
https://whitepaper.worldcoin.org/#biometrics

There is also an explanation here: [skip to 31:42](https://youtu.be/9m69EzhufCg?t=1903&si=-6as3fybyQooFUb7)

**Comment by rajjanorkar** [comment]
@TheButlah, thanks for your response! I'll review it thoroughly. For mass adoption, I was thinking if we could come up with an innovative solution that allows users to sign up on their own without needing custom hardware, we could achieve that more quickly. Of course, we'd still need to consider factors like privacy, uniqueness, and more.

**Comment by rajjanorkar** [comment]
@TheButlah thank you.
