### ISSUE TITLE
suspended worldcoin account

### ISSUE THREAD

**Issue by Hezzytemba** [worldcoin/orb-software#308]
why was my worldcoin account suspended

**Comment by TheButlah** [comment]
Hi, this github is for working on code and technical discussion and we don't have the tools to help you (we just work on code).
If you need help with you account, try checking out our [customer support page](https://support.world.org/hc/en-us).

**Comment by Hezzytemba** [comment]
Okay thank you

**Comment by Hezzytemba** [comment]
How can I recover a suspended world Coin account

**Comment by TheButlah** [comment]
Hi, you'll need to contact the link I provided, github doesn't have the tools to do customer support. Sorry!

**Comment by Hezzytemba** [comment]
Awesome, thanks for the update!
